version: '3.8'

services:
  frontend:
    image: node:22.16.0
    container_name: OfferAppUI
    working_dir: /src
    volumes:
      - ../src:/src
      - /src/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
